### ISSUE TITLE
Mermaid CLI  - upgrade to 8.5.1 - fails to parse graphs with stadium-style borders

### ISSUE THREAD

**Issue by tskir** [mermaid-js/mermaid#1403]
**Describe the bug**
Mermaid CLI fails to parse & render flowchart graphs which contain nodes with “stadium-style” borders.

**To Reproduce**
```bash
npm install @mermaid-js/mermaid-cli
cat << EOF > test.mmd
  graph LR
  A[Source] --> B([Destination])
EOF
./node_modules/.bin/mmdc -i test.mmd -o test.png
```

This gives the following error message:
```
(node:2595426) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 2:
...R  A[Source] --> B([Destination])
----------------------^
Expecting 'SPACE', 'GRAPH', 'DIR', 'subgraph', 'end', 'PS', 'TAGEND', '--', '==', 'STR', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DOWN', 'UP', 'DEFAULT', 'PCT', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'MINUS', 'BRKT', 'DOT', 'TAGSTART', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'SQS'
    at zt.parseError (file:///home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/@mermaid-js/mermaid-cli/mermaid.min.js:31:215251)
    at zt.parse (file:///home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/@mermaid-js/mermaid-cli/mermaid.min.js:31:216426)
    at pt (file:///home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/@mermaid-js/mermaid-cli/mermaid.min.js:41:240092)
    at Object.render (file:///home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/@mermaid-js/mermaid-cli/mermaid.min.js:41:300668)
    at Object.init (file:///home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/@mermaid-js/mermaid-cli/mermaid.min.js:48:216)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/helper.js:111:15)
    at ElementHandle.evaluate (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/JSHandle.js:54:42)
    at ElementHandle.<anonymous> (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.$eval (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/JSHandle.js:505:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.$eval (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/DOMWorld.js:156:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.$eval (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/Page.js:345:29)
    at Page.<anonymous> (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/puppeteer/lib/helper.js:112:23)
    at /home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:84:14
    at Generator.next (<anonymous>)
    at step (/home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:4:191)
    at /home/ktsukanov/repositories/eva-cttv-pipeline/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:4:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2595426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2595426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
I expect this graph which is produced by the live editor:
![mermaid-diagram-20200511162304](https://user-images.githubusercontent.com/10669118/81579149-b3941480-93a3-11ea-837a-3d9caf1ec944.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Mermaid CLI
 - Version: 8.4.8

**Additional context**
Mermaid is awesome, thank you for working on it! I find it a really useful and unique product.

**Comment by tskir** [comment]
I can additionally confirm that exact same error also happens when installing via Yarn

**Comment by knsv** [comment]
I think that the CLI needs to be updated to later version of mermaid

**Comment by GDFaber** [comment]
Hi @tskir, can you check if the issue still exists in mermaid 8.4.6?

**Comment by tskir** [comment]
Hi @GDFaber, I checked and can confirm that the issue is not present anymore. Not only for this simple example graph, but for our much more complicated workflow graph as well. Thanks a lot!
