### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by leejaehyun600319** [mermaid-js/mermaid#1603]
```
/Users/mac/Desktop/directoryname/node_modules/entity-decode/browser.js:8
export default function decode(html) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1106:15)
    at Module._compile (internal/modules/cjs/loader.js:1140:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.entity-decode/browser (/Users/mac/Desktop/example/markdown-remark/node_modules/mermaid/dist/mermaid.core.js:21471:18)
    at __webpack_require__ (/Users/mac/Desktop/directoryname/node_modules/mermaid/dist/mermaid.core.js:30:30)
```
After importing mermaid module to index.js file, this error message was shown in the console.

I think there might be a problem in the mermaid module but i don't know what it is.

**Comment by sidharthv96** [comment]
@leejaehyun600319 can you share how this was resolved?

I am facing the same issue when trying to use mermaid with svelte-kit.

**Comment by pjgoncalves** [comment]
Any updates on this?

**Comment by cskeogh** [comment]
I have the same error. I am using [Razzle](https://razzlejs.org/) server side rendering (SSR).

I solved the error with the following change to mermaid, rebuilt mermaid, and copied the build's `dist` to `./node_modules/mermaid/dist`:

```diff
diff --git a/src/mermaid.js b/src/mermaid.js
index 07728a5d..b42407f7 100644
--- a/src/mermaid.js
+++ b/src/mermaid.js
@@ -2,7 +2,7 @@
  * Web page integration module for the mermaid framework. It uses the mermaidAPI for mermaid functionality and to render
  * the diagrams to svg code.
  */
-import decode from 'entity-decode/browser';
+import decode from 'entity-decode';
 import { log } from './logger';
 import mermaidAPI from './mermaidAPI';
 import utils from './utils';
```

I haven't tested beyond my use-case.
