### ISSUE TITLE
Parse error in sequenceDiagram when autonumber is used

### ISSUE THREAD

**Issue by iwanzarembo** [mermaid-js/mermaid#1849]
I get a Parse error if I use the sequenceDiagram from [Getting Started Docs](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=sequencenumbers).
mermaid.cli version is 0.5.1

```
sequenceDiagram
    autonumber
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```

mmdc -i .\test_diag.mmd -o .\test_diag.png -t default
Results in:

```
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Evaluation failed: Error: Parse error on line 2:
...agram    autonumber    Alice->>John: H
----------------------^
Expecting 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', got 'NL'
    at x.parseError (file:///C:/Users/username/AppData/Local/Yarn/Data/global/node_modules/mermaid.cli/mermaid.min.js:1:423219)
    at x.parse (file:///C:/Users/username/AppData/Local/Yarn/Data/global/node_modules/mermaid.cli/mermaid.min.js:1:424385)
    at Object.e.draw (file:///C:/Users/username/AppData/Local/Yarn/Data/global/node_modules/mermaid.cli/mermaid.min.js:1:720085)
    at Object.render (file:///C:/Users/username/AppData/Local/Yarn/Data/global/node_modules/mermaid.cli/mermaid.min.js:1:760928)
    at s (file:///C:/Users/username/AppData/Local/Yarn/Data/global/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///C:/Users/username/AppData/Local/Yarn/Data/global/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async ExecutionContext.evaluate (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
    at async ElementHandle.evaluate (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\JSHandle.js:55:12)
    at async ElementHandle.$eval (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\JSHandle.js:478:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\helper.js:111:15)
    at ElementHandle.<anonymous> (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\helper.js:112:23)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.$eval (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\DOMWorld.js:156:21)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.$eval (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\Page.js:347:29)
    at Page.<anonymous> (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\puppeteer\lib\helper.js:112:23)
    at C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\mermaid.cli\index.bundle.js:83:14
    at Generator.next (<anonymous>)
    at step (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\mermaid.cli\index.bundle.js:4:191)
    at C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\mermaid.cli\index.bundle.js:4:361
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by knsv** [comment]
Are you sure you are using the latest version of mermaid? Perhaps an older version without suffucuent support is beeing used?

**Comment by iwanzarembo** [comment]
The latest version I could find today (10. January 2021) is 0.5.1, see also https://yarnpkg.com/package/mermaid.cli

**Comment by mmorel-35** [comment]
Have you tried this one : https://yarnpkg.com/package/@mermaid-js/mermaid-cli ? It seems like a more up-to-date version

**Comment by iwanzarembo** [comment]
Yes, that was the issue! The other package https://yarnpkg.com/package/mermaid.cli is the old one and it seems not to be used anymore. Would it be possible to update the package with a deprecation notice? And maybe even make it unworkable with reference to the correct package?

**Comment by BastianZim** [comment]
Just FYI, the repo of the CLI is https://github.com/mermaid-js/mermaid-cli
Maybe someone there has access to the old version?

**Comment by ashishjain0512** [comment]
Using the new yarn package location below for mermaid-cli works, as it uses the later version of Mermaid.js.

https://yarnpkg.com/package/@mermaid-js/mermaid-cli  

@tylerlong We have moved the mermaid-cli project under the mermaid-js org since we didn't have access to publish newer changes to the original project. Feel free to modify mermaid.cli as you see fit, however, our suggestion would be to modify its description or unpublish it from NPM.
