### ISSUE TITLE
Function.createFromInputFallback triggers deprecation warning

### ISSUE THREAD

**Issue by h-enk** [mermaid-js/mermaid#2166]
**Describe the bug**
> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

**To Reproduce**
1. Go to 'https://mermaid--doks.netlify.app/docs/prologue/quick-start/'
2. Open Chrome DevTools: <kbd>F12</kbd>
3. See warning

**Expected behavior**
No warning

**Screenshots**

![Snag_3567d0](https://user-images.githubusercontent.com/3902872/124080363-94928f00-da4a-11eb-9f32-52e942ca82dd.png)

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 3d, _f: , _strict: true, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:601444)
    at bD (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:619421)
    at bE (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:620140)
    at k (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:620221)
    at d (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:598266)
    at _ (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:873178)
    at g (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:875137)
    at B (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:875341)
    at Object.U [as getTasks] (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:872002)
    at Object.h [as draw] (https://mermaid--doks.netlify.app/js/mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1:877807)
bT @ mermaid.min.b88517fdf76595f3e849d42fcd409f2c7be7cd9f8c3b5898f071a177711faf38fccf6ed97210d62a2a22466921626b7f2381207d39fc17fe5adc8352a1361b4c.js:1
```
**Code Sample**
https://mermaid--doks.netlify.app/docs/prologue/quick-start/

**Desktop (please complete the following information):**
 - Windows 10 Pro 21H1 19043.1081
- Google Chrome Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by h-enk** [comment]
In addition, the dates (valid format) in the Gantt chart are triggering the error:

```
gantt
  section Section
  Completed :done,    des1, 2014-01-06,2014-01-08
  Active        :active,  des2, 2014-01-07, 3d
  Parallel 1   :         des3, after des1, 1d
  Parallel 2   :         des4, after des1, 1d
  Parallel 3   :         des5, after des3, 1d
  Parallel 4   :         des6, after des4, 1d
```

See also: https://momentjs.com/guides/#/warnings/js-date/

**Comment by h-enk** [comment]
This triggers no error:

```
gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d
```

I guess `dateFormat  YYYY-MM-DD` is needed :wink:
