### ISSUE TITLE
ERR_MODULE_NOT_FOUND during pnpm run dev

### ISSUE THREAD

**Issue by vallsv** [mermaid-js/mermaid#3607]
**Describe the bug**
I have tried to launch the E2E tests following the contribution page.
Bit when ever i launch `pnpm run dev`, it displays this error.

```
[1] /home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366
[1]     throw new ERR_MODULE_NOT_FOUND(
[1]           ^
[1] CustomError: Cannot find module '/home/valls/workspace/web/mermaid.git/.vite/server' imported from /home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/dist-raw/runmain-hack.js
[1]     at finalizeResolution (/home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
[1]     at moduleResolve (/home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
[1]     at Object.defaultResolve (/home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
[1]     at /home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/src/esm.ts:218:35
[1]     at entrypointFallback (/home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/src/esm.ts:168:34)
[1]     at /home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/src/esm.ts:217:14
[1]     at addShortCircuitFlag (/home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/src/esm.ts:409:21)
[1]     at resolve (/home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/src/esm.ts:197:12)
[1]     at resolve (/home/valls/workspace/web/mermaid.git/node_modules/.pnpm/ts-node@10.9.1_jrs6fgrkrfl5zdawlcdiuhuotq/node_modules/ts-node/src/child/child-loader.ts:15:39)
[1]     at nextResolve (node:internal/modules/esm/loader:163:28)
[1] ts-node-esm .vite/server exited with code 1
```
Any idea if it could explain that i can't execute successfully the E2E tests?

**Desktop (please complete the following information):**

- OS: Debian 10

**Additional context**

**Comment by vallsv** [comment]
Sounds like my PR fix my problem.
I am now able to launch the E2E tests.
