### ISSUE TITLE
`click` cannot be used for node IDs

### ISSUE THREAD

**Issue by kdeldycke** [mermaid-js/mermaid#4182]
### Description

I'm trying to render a graph with 2 nodes, literally named `click` and `click-extra`. The reason being that I'm trying to draw the dependency graph of my [Click Extra](https://github.com/kdeldycke/click-extra) Python project, which itself depends on [Click](https://click.palletsprojects.com/).

Naively, my first iteration of the graph is:
```text
flowchart TD
    click-extra
    click
    click-extra --> click
```

This doesn't work and crash the rendering.

### Steps to reproduce

Given the mermaid code above, let's try to render it:
```shell-session
$ cat ./click-reserved-keyword.mmd
flowchart TD
    click-extra
    click
    click-extra --> click
```

```shell-session
$ mmdc --input ./click-reserved-keyword.mmd --output output.png
Generating single mermaid chart

Error: Evaluation failed: Error: Diagram error not found.
    at pptr://__puppeteer_evaluation_script__:24:17
    at ExecutionContext._ExecutionContext_evaluate (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:251:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:140:16)
    at async CDPElementHandle.$eval (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ElementHandle.js:116:24)
    at async renderMermaid (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:216:22)
    at async parseMMD (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:188:20)
    at async run (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:438:20)
    at async cli (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:154:3)
```

The [live editor cannot renders it either](https://mermaid.live/edit#pako:eNpljEsKwzAMRK9itI4v4EVXuUG71EbISmPqTxEybQm5e1xKodBZDfMeswG3KBBgye3BK6m5y4zVjXBOfPPyNKWf4Y85709fBBMU0UIpjsftrSLYKkUQwqhRFurZELDuQ6Vu7fyqDMG0ywT9HslkTnRVKp9xPwBj0zVX):

<img width="1261" alt="Screenshot 2023-03-04 at 11 09 41" src="https://user-images.githubusercontent.com/159718/222882224-6201dfc3-8760-4da2-a18b-46b8460a326c.png">

And GitHub is giving up too:
```mermaid
flowchart TD
    click-extra
    click
    click-extra --> click
```

### Using double-quotes

The problem is that [double-quoting, which seems to be the way of handling special strings](https://mermaid.js.org/syntax/flowchart.html#special-characters-that-break-syntax), ends up with the same issue:
```shell-session
$ cat ./click-reserved-keyword-double-quoted.mmd
flowchart TD
    "click-extra"
    "click"
    "click-extra" --> "click"
```

```shell-session
$ mmdc --input ./click-reserved-keyword-double-quoted.mmd --output output.png
Generating single mermaid chart

Error: Evaluation failed: Error: Diagram error not found.
    at pptr://__puppeteer_evaluation_script__:24:17
    at ExecutionContext._ExecutionContext_evaluate (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:251:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:140:16)
    at async CDPElementHandle.$eval (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ElementHandle.js:116:24)
    at async renderMermaid (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:216:22)
    at async parseMMD (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:188:20)
    at async run (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:438:20)
    at async cli (file:///opt/homebrew/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:154:3)
```

The live [editor still doesn't like double-quoting](https://mermaid.live/edit#pako:eNpdjTEOwyAUQ6-CPIcLMHTKDdqR5Qs-CSqEin7UVlHuXjJEaurJtp7lFa54hkFI5eVmqqJuo11Ul4VL0d01v6WSxan8iwejtL78IhiQuWaKvj-s-8RCZs5sYbr1HKgl2cmto9SkXD-Lg5HaeEB7eBIeI02VMkyg9OTtC3gROZI):

<img width="1252" alt="Screenshot 2023-03-04 at 11 16 11" src="https://user-images.githubusercontent.com/159718/222882367-42a7420f-d7dc-4dff-8160-fc19bbeded48.png">

### Hackish workaround: simple quotes

Now dabbling with the live editor, I [found a way to have the graph rendered using simple quotes](https://mermaid.live/edit#pako:eNpljDsOwjAQRK8SbUOTRHY-xnZBxQ2gQm5WjgMRcYyMIz5R7o4JQhRMtfvmaSbQrjEgoe3dTZ_Qh2S_VUMSo_tOnzNzDx4_YLWQ1V-bZNnmV0IK1niLXRNXp7esIJyMNQpkPBvT4tgHBWqYo4pjcLvHoEEGP5oUxkuDwWw7PHq0IFvsr5FecDg4Z79SfEFOcAdZkDovy6JkghJOal6xFB5vnNM1J0JQyipOqSjmFJ7LAskrsYSzihSiZmJ-AfSRTgA):

<img width="1267" alt="Screenshot 2023-03-04 at 11 22 06" src="https://user-images.githubusercontent.com/159718/222882396-76a3532f-1a15-4fd3-9736-753b32954fa9.png">

That's a fun hack but should be considered a false-positive case.

### Setup

Example above have been produce with both local CLI (on macOS) and online Live Editor with v10.0.0:
```shell-session
$ mmdc --version
10.0.0
```

### Additional Context

All examples above are the minimally reproducible issue, inspired from [the real, full-featured dependency graph I'm trying to render](https://github.com/kdeldycke/click-extra/blob/main/docs/images/dependencies.mmd?short_path=7bed43d).

And BTW, adding links to diagrams with the [`click` directive](https://mermaid.js.org/syntax/flowchart.html#interaction) is a fantastic feature!

**Comment by sidharthv96** [comment]
`click` is a reserved keyword. So you can add a nodeID there.

```
flowchart TD
    click-extra
    C[click]
    click-extra --> C
```

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/10703445/222884960-b0e000f3-d219-427f-8eb5-b1838e0b047d.png">

**Comment by kdeldycke** [comment]
Thanks @sidharthv96 for the fast reply! If `click` is a keyword as per the Mermaid spec then fine, I'll try to circumvent that limitation in my code generation.

To make my code future proof, is there a list somewhere which defines all reserved words we have to avoid? Thanks in advance! :)

**Comment by kdeldycke** [comment]
> To make my code future proof, is there a list somewhere which defines all reserved words we have to avoid? Thanks in advance! :)

Playing with the live editor, I identified these strings as reserved keywords:
```python
reserved_ids = {
    "C4Component", "C4Container", "C4Deployment", "C4Dynamic", "_blank", "_parent",
    "_self", "_top", "call", "class", "classDef", "click", "end", "flowchart",
    "flowchart-v2", "graph", "interpolate", "linkStyle", "style", "subgraph"
}
```
