### ISSUE TITLE
subgraph link bug

### ISSUE THREAD

**Issue by oraant** [mermaid-js/mermaid#4508]
### Description

trying to draw something like this:

```
flowchart BT

subgraph A
	subgraph AA
		AAA
	end
end

subgraph a
	subgraph aa
		aaa
	end
end

a --> A
aa --> AA
aaa --> AAA
```

### Steps to reproduce

but if you delete `aaa --> AAA`, boom! render failed.

### Code Sample

```text
flowchart BT

subgraph A
	subgraph AA
		AAA
	end
end

subgraph a
	subgraph aa
		aaa
	end
end

a --> A
aa --> AA
```
```


### Setup

- Mermaid version: 10.2.3
- Browser and Version: [Edge]

### Additional Context

_No response_

**Comment by nirname** [comment]
```mermaid
flowchart BT

subgraph B
	subgraph BB
		BBB
	end
end 

subgraph A
	subgraph AA
		AAA
	end
end

A -->B;
BB-->AA;
```

```
View.669324eb.js:3 view fail TypeError: Cannot read properties of undefined (reading 'id')
    at index-1e7f2254.c8c71bd0.js:1:10249
    at Array.map (<anonymous>)
    at $ (index-1e7f2254.c8c71bd0.js:1:9522)
    at index-1e7f2254.c8c71bd0.js:1:9912
    at Array.map (<anonymous>)
    at $ (index-1e7f2254.c8c71bd0.js:1:9522)
    at gt (index-1e7f2254.c8c71bd0.js:1:11488)
    at Object.le [as draw] (styles-7882abfe.1296b518.js:2:1390)
    at Object.render$1 [as render] (state.f87e7922.js:87:1021)
```
