### ISSUE TITLE
i have problem to import mermaid from "mermaid"

### ISSUE THREAD

**Issue by FaryarKankash** [mermaid-js/mermaid#5081]
### Description

i cant use mermaid in my node js project, every time i want to import it , it give me an error 
 the error is:
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\*\*\Desktop\mermaid-js\node_modules\mermaid\dist\mermaid.core.mjs not supported.
Instead change the require of C:\Users\farya\Desktop\mermaid-js\node_modules\mermaid\dist\mermaid.core.mjs to a dynamic import() which is available in all CommonJS modules.

node version: 18.16.1
npm version: 9.5.1

### Steps to reproduce

1. simple just import mermaid from "mermaid"
2. use it console.log(mermaid);
3. ts-node index.ts

### Code Sample

```text
import mermaid from "mermaid"

console.log(mermaid);
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by vvscode** [comment]
@sidharthv96  sorry, but I get the same error on using cli

```
➜  __tools git:(master) ✗ npx mmdc _logs/mermaid.mmd
/Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/string-width/index.js:2
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/strip-ansi/index.js from /Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/string-width/index.js not supported.
Instead change the require of /Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/strip-ansi/index.js in /Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/string-width/index.js:2:19) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v21.4.0

```

**Comment by sidharthv96** [comment]
@vvscode I'm not sure how close your error is related to mermaid. As the package is not mentioned in the stack trace. The CLI also doesn't `require` mermaid directly, but imports it inside a webpage. @aloisklink can confirm.

**Comment by vvscode** [comment]
```
➜  __tools git:(master) ✗ node node_modules/@mermaid-js/mermaid-cli/src/cli.js
/Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/string-width/index.js:2
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/strip-ansi/index.js from /Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/string-width/index.js not supported.
Instead change the require of /Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/strip-ansi/index.js in /Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/string-width/index.js:2:19)
    at Object.<anonymous> (/Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/cliui/build/index.cjs:291:21)
    at Object.<anonymous> (/Users/v.vanchuk/repo/pwa-ib/__tools/node_modules/yargs/build/index.cjs:1:60683)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
```

does this make more clear, that the problem is somewhere there? =)

**Comment by aloisklink** [comment]
Hmmmmm, @vvscode, it looked like you somehow downloaded a version of [`string-width`](https://www.npmjs.com/package/string-width) that was incompatible with your version of  [`strip-ansi`](https://www.npmjs.com/package/strip-ansi). Maybe an older version of these packages had a bug in them?

It's good that you got the issue fixed, but if you do have any other issues with the CLI, please feel free to make an issue in https://github.com/mermaid-js/mermaid-cli :)
