### ISSUE TITLE
[Flowchart] Error with self-reference

### ISSUE THREAD

**Issue by Spixmaster** [mermaid-js/mermaid#5282]
### Description

Generating a flowchart element which depends on itself causes an error. This was not the case in prior versions like the recent one from August 2023.

### Steps to reproduce

Used command: `mmdc -c "${XDG_CONFIG_HOME}"/mermaid/mermaid.json -f -i input.mmd -o output.pdf`

Config file:
```json
{
    "maxEdges": 999999,
    "maxTextSize": 999999,
    "theme": "dark"
}
```

Output:
```sh
Generating single mermaid chart

Error: Evaluation failed: DOMException: Failed to execute 'structuredClone' on 'Window': function jW(t){return new sBA(t)} could not be cloned.
    at file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/dist/index.html:118:5524
    at Array.forEach (<anonymous>)
    at $Pt (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/dist/index.html:118:4924)
    at QGA (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/dist/index.html:118:13704)
    at Object.BOt [as draw] (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/dist/index.html:119:1284)
    at Object.m8t [as render] (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/dist/index.html:87:1415)
    at ExecutionContext._ExecutionContext_evaluate (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:254:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:143:16)
    at async CDPJSHandle.evaluate (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/JSHandle.js:56:16)
    at async CDPElementHandle.$eval (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ElementHandle.js:86:24)
    at async renderMermaid (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:246:22)
    at async parseMMD (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:218:20)
    at async run (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:479:20)
    at async cli (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:184:3)
```

### Code Sample

```text
flowchart LR
    %% Materialtyp
    materialtyp --> materialtyp %% This line causes the issue.

    subgraph materialtyp["Materialtyp"]
        direction LR
        style materialtyp fill:#2FEFCC
        materialtyp-start(("Materialtyp"))
        materialtyp-operation["# Materialtyp erstellen
- *Verwaltung > Struktur > Taxonomie > Materialtyp*
- Kategorisierung von Materialien"]
        materialtyp-dokument[/"Materialtyp"/]
        materialtyp-ende([" "])
        materialtyp-start --> materialtyp-operation --> materialtyp-dokument --> materialtyp-ende
    end
```

### Setup

- version mermaid-cli: 10.8.0
- Browser and Version: mhromium 121.0.6167.160

**Comment by Spixmaster** [comment]
I just tested some versions.

v10.3.1: works
v10.4.0: works
v10.5.0: does not work
v10.7.0: does not work
v10.8.0: does not work

**Comment by Spixmaster** [comment]
I just test version 11.1.1 and it does not have the bug anymore.
