### ISSUE TITLE
vite build failure for 10.9.0

### ISSUE THREAD

**Issue by jesse23** [mermaid-js/mermaid#5362]
### Description

Vite build fails with vite-react-swc in 10.9.0

### Steps to reproduce

1. Mermaid Impl: https://github.com/jesse23/copilot/blob/mermaid_109_issue/apps/ui/src/components/MermaidDiagram.tsx
2. Build config: https://github.com/jesse23/copilot/blob/mermaid_109_issue/apps/ui/vite.config.ts
Result: `npm run dev` pass. `npm run build & npm run preview` will have error in browser as
```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'prototype')
    at kS (index-a6050d12.js:564:23131)
    at index-a6050d12.js:564:26435
    at index-a6050d12.js:1608:2692
```

9.4 seems to be fine (yeah the API is slightly different with `renderAsync`

### Setup

- Mermaid version: 10.9
- Browser and Version: Chrome

**Comment by sidharthv96** [comment]
Can you try v10.8.0 (to see if it's a issue with v10.9.0, or a difference between v9 and v10)?

And please provide a minimum reproduction, instead of a complete project.

**Comment by jesse23** [comment]
Yeah I'll try to update before Monday. Thx!

**Comment by BossHogg97** [comment]
Hi, i have the same error but in a Vue3 application with vite. 

Here the code i wrote:
```ts
<script setup lang="ts">
  import mermaid from 'mermaid' // https://mermaid.js.org/config/usage.html

  type Props = {
    source?: string
  }
  const props = defineProps<Props>()

  let mermaidAPI = mermaid.mermaidAPI
  console.log('mermaidAPI: ', mermaidAPI)
  mermaidAPI.initialize({
    startOnLoad: false,
    securityLevel: 'sandbox'
  })

  setTimeout(async () => {
    await render(props.source)
  }, 1200)

  async function render(str) {
    let id = 'customGraph'
    const { svg } = await mermaidAPI.render(`mermaid-${id}`, str)
    document.getElementById('dynamicDiagram').innerHTML = svg
  }
</script>

<template>
  <div border-solid border-1 rounded-md border-slate-200>
    <n-card hoverable :bordered="false">
      <div class="flex mx-auto my-auto" :style="{ height: '700px' }">
        <div id="dynamicDiagram"></div>
      </div>
    </n-card>
  </div>
</template>

<style>
  #dynamicDiagram {
    padding-left: 2em;
    flex: 1;
  }
</style>
```

Thanks

**Comment by wong2** [comment]
This still occurs in v11.6

**Comment by code-alexander** [comment]
I was able to resolve this by adding an alias to my vite config:

```
  resolve: {
    alias: {
      mermaid: path.join(
        __dirname,
        "node_modules/mermaid/dist/mermaid.esm.min.mjs"
      ),
    },
  },
```
