### ISSUE TITLE
Block diagram: Converting circular structure to JSON

### ISSUE THREAD

**Issue by OleksiiParastiukSage** [mermaid-js/mermaid#5530]
### Description

I am currently using `next.js@13.5.6` with `next-mdx-remote@4.41` and `mermaid@10.9.1` installed via npm to create static content. I am able to render every `mermaid` diagram except for "block-beta". API call to `mermaid.render` fails with the following error.

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLHtmlElement'
    |     property '__reactFiber$yacdp2ofu2' -> object with constructor 'uk'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at 7877.06c80a12bd10709f.js:1:32088
    at Object.draw (7877.06c80a12bd10709f.js:1:32555)
    at async Object.render$1 [as render] (bc6b29d3-49f0478c8337dde7.js:61:1716)
```

When object is inspected in the console, it contains the endless structure.
![Screenshot 2024-05-17 111356](https://github.com/mermaid-js/mermaid/assets/167298031/31f069c6-9701-48ba-8a4e-a8349fbda403)

I have a very simple rendering logic placed inside `useEffect` inside a custom component that replaces `code` element in markdown files. Unfortunately, I am not able to share the code or provide it in live environment.

### Steps to reproduce

Unfortunately, I was not able to reproduce this issue in other projects, so I suspect the issue to be project specific.

### Code Sample

```text
useEffect(() => {
        const render = async () => {
              try {
                  const type = mermaid.detectType(text)
                  const { svg } = await mermaid.render(type, text)
                  setSvg(svg)
              } catch (error) {
                  console.log('ERROR', error)
              }
        }

        render()
    }, [])
```

### Setup

- Mermaid version: 10.9.1
- Browser and Version: Chrome 125

**Comment by OleksiiParastiukSage** [comment]
Update to the issue: the block successfully renders if the logger line inside node modules is removed.
![Screenshot 2024-05-21 120719](https://github.com/mermaid-js/mermaid/assets/167298031/93fe6cde-03c2-4abb-80b6-46b029f09b75)

**Comment by OleksiiParastiukSage** [comment]
@MikeAndFriends

Hi, I simply don't use this chart. Finding that log statement was just me curios about why doesn't it work.
If you absolutely need to make this chart to work, you would probably need to create a fork and remove these log statements yourself. Unfortunately, I don't have any other solution to share.

**Comment by mariusziemke** [comment]
This issue is related to react adding debug information to HTML Elements (https://github.com/facebook/react/issues/24360)

Can be fixed (quite dirty) by using:

```ts
// Fix a bug with mermaid block diagrams in react.
//
// relates to:
// https://github.com/facebook/react/issues/24360
// https://github.com/mermaid-js/mermaid/issues/5530
(HTMLElement.prototype as any).toJSON = () => "";
```

maybe that helps :)

**Comment by YuJaejun** [comment]
@mariusziemke It works for me. Thank you!!
